# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MF Optimization Tools
author: Raphael Strickling
logo: content/figures/logo.tiff
copyright: "2026"

exclude_patterns: [build, .DS_Store]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
  latex_enginge: xelatex

# sphinx extensions, e.g. docstrings
sphinx:
  extra_extensions:
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.napoleon'
    - 'sphinx.ext.viewcode'
    - 'sphinx_autodoc_typehints'
  config:
    project: "Optimization Tools"


# Add GitHub button
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

repository:
  url: https://github.com/raphStrickling/MFoptimizationTools
  branch: main
  path_to_book: doc
