"""
surrogateTools
==============

This package contains useful tools for importing surrogate models from Dakota.
"""

import numpy as np
from functools import partial


def _polynomial(x: np.ndarray, coeffs: np.ndarray, exponent_mat: np.ndarray):
    """
    Evaluate a polynomial of the form

    .. math::
        y(x) = \\sum_k c_k \\left(\\prod_i x_i ^{p_{k,i}} \\right)

    :param x: point to evaluate
    :type x: np.ndarray, shape (n_design_variables,)
    :param coeffs: coefficients c_k in the polynomial
    :type coeffs: np.ndarray, shape (n_bases,)
    :param exponent_mat: matrix of exponents in the polynomial
    :type exponent_mat: np.ndarray, shape (n_bases, n_design_variables)
    """
    # enable evaluation of multiple points (n_points, n_DV)
    x = np.atleast_2d(np.asarray(x, dtype=float))
    n_DV = exponent_mat.shape[1]

    if x.shape[1] != n_DV:
        raise ValueError(
            f"x must contain all design variables (found number of design variables: {x.shape[1]}, expected {n_DV})"
        )

    # vectorized exponentiation
    monomials = np.prod(x[:, np.newaxis, :] ** exponent_mat[np.newaxis, :, :], axis=-1)
    y = monomials @ coeffs
    return np.squeeze(y)


def _surfpack_gaussian_process(parameters: dict) -> callable:
    """
    Calculate objective function value using a gaussian process surrogate model.

    :param parameters: dictionary containing the parameters for the kriging model. This dictionary can be obtained using the :py:func:`_parse_gaussian_process_input` function and the corresponding .alg file:

        - **Xshift** (``np.ndarray`` of size (1, n_DV)): shift vector used for normalizing the design variables to [-0.5, 0.5]
        - **Xmult** (``np.ndarray`` of size (1, n_DV)): normalization factors for normalizing the design variables to [-0.5, 0.5]

        .. math::
            x_{i,\\text{scaled}} = \\frac{x_i - x_{i,\\text{shift}} }{x_{i,\\text{mult}}}

        - **Yshift** (``float``): shift value for normalizing the dependent variable to [-0.5, 0.5]
        - **Ymult** (``float``): normalization factor for normalizing the dependent variable to [-0.5, 0.5]
        - **c** (``np.ndarray`` of size (1, n_bases)): Coefficients for trend function in GP
        - **p** (``np.ndarray`` of size (n_bases, n_DV)): Exponents for trend function in GP
        - **corr** (``np.ndarray`` of size (1, n_DV)): correlation vector
        - **xbuild** (``np.ndarray`` of size (n_DV, n_samples): sampling points on which the kriging model was built
        - **m** (``np.ndarray`` of size (n_samples, 1)): parameter
    :return: function handle of the surrogate model. This function handle takes a vector of design variables as an argument.
    """
    Xshift = parameters["Xshift"][0]
    Xmult = parameters["Xmult"][0]
    Yshift = parameters["Yshift"][0]
    Ymult = parameters["Ymult"][0]
    c = parameters["c"][0]
    p = parameters["p"]
    corr = parameters["corr"][0]
    xbuild = parameters["xbuild"]
    m = parameters["m"]

    n_DV = len(Xshift)  # number of design variables

    def normalize_x(x, Xshift, Xmult):
        """
        Normalize x to be between -0.5 and 0.5
        """
        return (x - Xshift) / Xmult

    def squared_exp_kernel(x) -> np.array:
        """
        Squared exponential kernel for approximating a two-point correlation. This is the default Gaussian Process Regression Kernel in Dakota.

        .. math::
            R(x, x_j) = \\text{exp} \\left( - \\sum_i^m \\theta_{i} (x_{i} - x_{i,j})^2 \\right)

        """
        # diff = x_i - x_ij
        diff = x[:, np.newaxis, :] - xbuild.T[np.newaxis, :, :]
        # sum diff^2 over n_DV (index i)
        exponent_sum = np.einsum("jki,i->jk", diff**2, corr)
        return np.exp(-exponent_sum)

    def kriging(x):
        """
        Construct a Kriging model using a trend function h, and a stationary random process Z

        .. math::
            Y(x) = h(x) + Z(x)

        The random process is modeled using the squared exponential kernel for approximation
        the two-point correlation

        .. math::
            Z(x) = \\sum_j^n R(x, x_j) * m_j

        """
        x = np.atleast_2d(np.asarray(x, dtype=float))
        if x.shape[1] != n_DV:
            raise ValueError(
                f"x must contain all design variables (found number of design variables: {x.shape[1]}, expected {n_DV})"
            )
        xs = normalize_x(x, Xshift, Xmult)
        R = squared_exp_kernel(xs)
        ynorm = _polynomial(xs, c, p) + R @ m
        return np.squeeze(Ymult * ynorm + Yshift)

    return kriging


def _parse_gaussian_process_input(path: str) -> dict:
    """
    Extract parameters for a Gaussian Process Regression surrogate model from an .alg file generated by Dakota.

    :param path: path to .alg file containing the parameters for the Gaussian Process Regression surrogate model
    :return: dictionary formatted for the function :py:func:`_surfpack_gaussian_process`
    """
    n_DV = 0
    n_bases = 0
    n_samples = 0
    linesLeft = 0

    inputs = {"Xshift": [], "Xmult": [], "Yshift": [], "Ymult": [], "c": [], "p": [], "corr": [], "xbuild": [], "m": []}

    activeVar = ""
    with open(path) as inputFile:
        for line in inputFile.readlines():
            if linesLeft != 0:
                vector = line.split(" ")
                vector = list(filter(len, vector))
                if "\n" in vector:
                    vector.remove("\n")
                if len(vector) == 1 and activeVar in ["Yshift", "Ymult", "m"]:
                    vector = vector[0]
                inputs[activeVar].append(vector)
                linesLeft -= 1

            if "inputs = " in line:
                n_DV = int(line.split(" ")[-1])
            elif "bases = " in line:
                n_bases = int(line.split(" ")[-1])
            elif "build = " in line:
                n_samples = int(line.split(" ")[-1])

            expectedShapes = {
                "Xshift": [1, n_DV],
                "Xmult": [1, n_DV],
                "Yshift": [1],
                "Ymult": [1],
                "c": [1, n_bases],
                "p": [n_bases, n_DV],
                "corr": [1, n_DV],
                "xbuild": [n_DV, n_samples],
                "m": [n_samples],
            }
            for var in inputs:
                if var + " (" in line:
                    activeVar = var
                    linesLeft = expectedShapes[activeVar][0]

    # convert to numpy arrays with floats
    for key, val in inputs.items():
        inputs[key] = np.array(val, dtype=float)
        # make sure that everything has been found
        if inputs[key].shape != tuple(expectedShapes[key]):
            raise ValueError(f"{key} should have shape {tuple(expectedShapes[key])}, but has shape {inputs[key].shape}")
    return inputs


def _parse_surfpack_polynomial_input(path: str) -> dict:
    """
    Extract parameters for a polynomial surrogate model from an .alg file generated by Dakota.

    :param path: path to .alg file containing the parameters for the polynomial surrogate model
    :return: dictionary formatted for the function :py:func:`_surfpack_polynomial`
    """
    n_DV = 0
    n_bases = 0
    linesLeft = 0

    inputs = {"c": [], "p": []}

    activeVar = ""
    with open(path) as inputFile:
        for line in inputFile.readlines():
            if linesLeft != 0:
                vector = line.split(" ")
                vector = list(filter(len, vector))
                if "\n" in vector:
                    vector.remove("\n")
                if len(vector) == 1:
                    vector = vector[0]
                inputs[activeVar].append(vector)
                linesLeft -= 1

            if "inputs = " in line:
                n_DV = int(line.split(" ")[-1])
            elif "bases = " in line:
                n_bases = int(line.split(" ")[-1])

            expectedShapes = {"c": [1, n_bases], "p": [n_bases, n_DV]}

            for var in inputs:
                if var + " (" in line:
                    activeVar = var
                    linesLeft = expectedShapes[activeVar][0]

    # convert to numpy arrays with floats
    for key, val in inputs.items():
        inputs[key] = np.array(val, dtype=float)
        # make sure that everything has been found
        if inputs[key].shape != tuple(expectedShapes[key]):
            raise ValueError(f"{key} should have shape {tuple(expectedShapes[key])}, but has shape {inputs[key].shape}")
    return inputs


def load_gaussian_process_surfpack(path: str) -> callable:
    """
    Load a gaussian process surrogate model that was constructed with Dakota using the surfpack format

    :param path: path to .alg file that is generated by Dakota
    :return: function handle of the surrogate model. This function handle takes a vector of design variables as an argument.
    """
    params = _parse_gaussian_process_input(path)
    return _surfpack_gaussian_process(params)


def load_polynomial_surfpack(path: str) -> callable:
    """
    Load a polynomial surrogate model that was constructed with Dakota using the surfpack format

    :param path: path to .alg file that is generated by Dakota
    :return: function handle of the polynomial model. This function handle takes a vector of design variables as an argument.
    """
    params = _parse_surfpack_polynomial_input(path)
    return partial(_polynomial, coeffs=params["c"][0], exponent_mat=params["p"])
