name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Required for GitHub Pages deployment
permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install toolbox
      run: |
        conda env create --file environment.yml
    - name: Test with pytest
      run: |
        conda run -n geom_opt pip install -e .[test]
        conda run -n geom_opt pytest . --cov-report=xml
    - name: Deploy documentation
      run: |
        conda run -n geom_opt pip install -e .[doc]
        cd doc/
        rm -rf _build
        conda run -n geom_opt sphinx-apidoc -o content/modules/ ../optimizationTools/ -E -d 3 -P -M -f --implicit-namespace
        conda run -n geom_opt jupyter-book build . --toc _toc.yml
        cd -
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'   # only deploy on push to main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/_build/html
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      fail_ci_if_error: false
